print("Enter your name: ")
a=input()
print("your name is...",a)
b=input("Enter your age: ") 
print("your age is...",b)
x=input("enter first number: ")
y=input("enter second number: ")
print(int(x)+int(y))